#!/bin/bash

# find shorthand
function f() {
  find . -name "*$1*" 2>&1 | grep -v 'Permission denied'
}

# Starts a rails server on the port 300{ARG} or port 3000 if no ARG
function rr() {
  port="${1-3000}"
  if [ "${port}" -lt 10 ];then
    port="300${port}"
  fi
  bundle exec rails s -p "${port}"
}

pr() {
  branch=$(git symbolic-ref HEAD | sed 's!refs\/heads\/!!')
  remote=$(git remote -v \
    | grep -m 1 "(push)" \
    | grep origin \
    | sed -e "s/.*github\.com[:\/]\(.*\) (push).*/\1/" \
    | sed "s/.git//")
  open "https://github.com/${remote}/pull/new/${branch}"
}

function killport() {
  app=`lsof -i tcp:$1 | tail -1`
  pid=`echo $app | awk '{ print $2;}'`
  if [ -z "$pid" ];then
    echo "No process found running on port $1"
  else
    echo $app
    echo "killing process with PID=$pid"
    kill -9 $pid
    echo "done"
  fi
}
