set nocompatible              " required for vundle
filetype off                  " required for vundle

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'git@github.com:wincent/command-t.git'

call vundle#end()

filetype plugin indent on    " required for vundle
