set nocompatible              " required for vundle
filetype off                  " required for vundle

" ================ General Config ====================

set number                      "Line numbers are good
set history=1000                "Store lots of :cmdline history
set showcmd                     "Show incomplete cmds down the bottom
set visualbell                  "No sounds
set autoread                    "Reload files changed outside vim
set ruler                       "Show cursor column/row information
set hidden

let mapleader=","

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree.git'
Plugin 'jistr/vim-nerdtree-tabs.git'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'skwp/vim-colors-solarized'
Plugin 'mileszs/ack.vim'
Plugin 'cyphactor/vim-open-alternate'

call vundle#end()

" ================ Styles ==============

set background=dark
silent! colorscheme solarized

" ================ Turn Off Swap Files ==============

set noswapfile
set nobackup
set nowb

" ================ Indentation ======================

set autoindent
set smartindent
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab

filetype plugin indent on    " required for vundle

" Display tabs and trailing spaces visually
set list listchars=tab:\ \ ,trail:·

" ================ Nerdtree ===========================
"
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1
let g:NERDTreeWinSize = 30

" Nerdtree tabs
let g:nerdtree_tabs_open_on_gui_startup = 0
let g:nerdtree_tabs_focus_on_files = 1

" If currently on a file opens NERDTree otherwise toggle it
function! OpenNerdTree()
  if &modifiable && strlen(expand('%')) > 0
    NERDTreeFind
  else
    NERDTreeToggle
  endif
endfunction

" ================ Search ===========================

set incsearch       " Find the next match as we type the search
set hlsearch        " Highlight searches by default
set ignorecase      " Ignore case when searching...
set smartcase       " ...unless we type a capital

" Configure the_silver_searcher for ack
if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

" Configure the_silver_searcher for ctrlp (speed boost)
let g:ctrlp_cache_dir = $HOME . '/.cache/ctrlp'
if executable('ag')
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
endif

" ================ Mappings ========================
noremap <leader>t :CtrlP<Cr>

" Open the Ack command and place the cursor into the quotes
nmap ,ag :Ack ""<Left>

" ,oq to open it back up (rare)
nmap <silent> ,qc :cclose<CR>
nmap <silent> ,qo :copen<CR>

" Open vim-open-alternate on a new vsplit window
nmap <leader>. :vs<Cr> :OpenAlternate<Cr>

" Open Nerdtree with Ctrl-\
nnoremap <silent> <C-\> :call OpenNerdTree()<CR>
